name: Fetch CSV

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"
          cache: "pip"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Fetch CSV
        run: python ./scripts/fetch.py
      - name: Set current datetime as env variable
        env:
          TZ: "Asia/Tokyo"
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - name: Commit and push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "53847253+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "${{ env.CURRENT_DATETIME }}: fetch papers" --allow-empty
          git push
